export const EQUIPO_TYPE_SUGGESTIONS = [
  'Cardiodesfibrilador',
  'Neo Puff',
  'Incubadora de Transporte',
  'Electrocardiógrafo',
  'Saturómetro',
  'Otoscopio',
  'Aspirador',
  'Glucómetro',
  'Aparato PA',
  'Bomba de Infusión'
];

export const EQUIPO_ESTADO_OPTIONS = ['activo', 'inactivo', 'roto', 'reparacion'];

export const EQUIPO_UBICACION_OPTIONS = ['base', 'vehiculo', 'economato', 'backup'];

export const su_equipos_biomedicos = [
  {
    id: 'eq1',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Cardiodesfibrilador',
    marca: 'NIHON KOHDEN',
    modelo: 'TEC-5631',
    numero_serie: 'NK-AVA-1101',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b1',
    vehiculo_id: 'v1',
    fecha_ultima_revision: '2026-07-20',
    fecha_proximo_service: '2026-09-14',
    estado: 'activo',
    observacion: 'Sin novedades'
  },
  {
    id: 'eq2',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Cardiodesfibrilador',
    marca: 'NIHON KOHDEN',
    modelo: 'TEC-5621',
    numero_serie: 'NK-AVA-1130',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b1',
    vehiculo_id: 'v2',
    fecha_ultima_revision: '2026-06-30',
    fecha_proximo_service: '2026-08-25',
    estado: 'activo',
    observacion: 'Control de batería pendiente de recambio'
  },
  {
    id: 'eq3',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Cardiodesfibrilador',
    marca: 'NIHON KOHDEN',
    modelo: 'TEC-5600',
    numero_serie: 'NK-BAS-2205',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b2',
    vehiculo_id: 'v3',
    fecha_ultima_revision: '2026-07-12',
    fecha_proximo_service: '2026-09-08',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq4',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Cardiodesfibrilador',
    marca: 'NIHON KOHDEN',
    modelo: 'TEC-5531',
    numero_serie: 'NK-PED-2112',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b2',
    vehiculo_id: 'v4',
    fecha_ultima_revision: '2026-05-11',
    fecha_proximo_service: '2026-08-18',
    estado: 'reparacion',
    observacion: 'Sin etiqueta de service visible'
  },
  {
    id: 'eq5',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Cardiodesfibrilador',
    marca: 'NIHON KOHDEN',
    modelo: 'TEC-5541',
    numero_serie: 'NK-AVA-3098',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b3',
    vehiculo_id: 'v5',
    fecha_ultima_revision: '2026-08-02',
    fecha_proximo_service: '2026-10-06',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq6',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Electrocardiógrafo',
    marca: 'COMEN',
    modelo: 'CM1200B',
    numero_serie: 'ECG-CM-177',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b4',
    vehiculo_id: 'v8',
    fecha_ultima_revision: '2026-05-02',
    fecha_proximo_service: '2026-08-10',
    estado: 'inactivo',
    observacion: 'Roto'
  },
  {
    id: 'eq7',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Electrocardiógrafo',
    marca: 'FUKUDA',
    modelo: 'FX-8222',
    numero_serie: 'ECG-FK-154',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b2',
    vehiculo_id: 'v9',
    fecha_ultima_revision: '2026-07-28',
    fecha_proximo_service: '2026-09-20',
    estado: 'activo',
    observacion: 'Sin etiqueta'
  },
  {
    id: 'eq8',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Saturómetro',
    marca: 'CHOISE MED',
    modelo: 'MD300C2',
    numero_serie: 'SAT-CM-220',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b4',
    vehiculo_id: 'v7',
    fecha_ultima_revision: '2026-07-15',
    fecha_proximo_service: '2026-09-01',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq9',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Saturómetro',
    marca: 'CHOISE MED',
    modelo: 'MD300C29',
    numero_serie: 'SAT-CM-146',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b3',
    vehiculo_id: 'v6',
    fecha_ultima_revision: '2026-04-18',
    fecha_proximo_service: '2026-08-12',
    estado: 'inactivo',
    observacion: 'Roto'
  },
  {
    id: 'eq10',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Aspirador',
    marca: 'YUEWELL',
    modelo: '7E-A',
    numero_serie: 'ASP-YW-101',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b1',
    vehiculo_id: 'v1',
    fecha_ultima_revision: '2026-08-05',
    fecha_proximo_service: '2026-11-01',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq11',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Glucómetro',
    marca: 'FREE STYLE',
    modelo: 'Optium Neo',
    numero_serie: 'GLU-FS-112',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b2',
    vehiculo_id: 'v4',
    fecha_ultima_revision: '2026-08-01',
    fecha_proximo_service: '2026-12-01',
    estado: 'activo',
    observacion: 'Equipo nuevo en móvil backup'
  },
  {
    id: 'eq12',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Glucómetro',
    marca: 'FREE STYLE',
    modelo: 'Optium',
    numero_serie: 'GLU-FS-205',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b2',
    vehiculo_id: 'v3',
    fecha_ultima_revision: '2026-08-07',
    fecha_proximo_service: '2026-10-15',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq13',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Aparato PA',
    marca: 'OMRON',
    modelo: 'HEM-7320',
    numero_serie: 'PA-OM-130',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b1',
    vehiculo_id: 'v2',
    fecha_ultima_revision: '2026-08-22',
    fecha_proximo_service: '2027-02-22',
    estado: 'activo',
    observacion: 'Equipo nuevo'
  },
  {
    id: 'eq14',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Aparato PA',
    marca: 'OMRON',
    modelo: 'HEM-7156',
    numero_serie: 'PA-OM-098',
    ubicacion_tipo: 'vehiculo',
    base_id: 'b3',
    vehiculo_id: 'v5',
    fecha_ultima_revision: '2026-07-21',
    fecha_proximo_service: '2026-09-11',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq15',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Bomba de Infusión',
    marca: 'TERUMO',
    modelo: 'TE-SS700',
    numero_serie: 'BINF-TER-001',
    ubicacion_tipo: 'economato',
    base_id: null,
    vehiculo_id: null,
    fecha_ultima_revision: '2026-05-16',
    fecha_proximo_service: '2026-08-05',
    estado: 'activo',
    observacion: 'Pendiente recalibración'
  },
  {
    id: 'eq16',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Neo Puff',
    marca: 'Fisher & Paykel',
    modelo: 'Neopuff RD900',
    numero_serie: 'NP-EC-001',
    ubicacion_tipo: 'economato',
    base_id: null,
    vehiculo_id: null,
    fecha_ultima_revision: '2026-08-10',
    fecha_proximo_service: '2026-12-10',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq17',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Incubadora de Transporte',
    marca: 'FANEM',
    modelo: 'IT-158 TS',
    numero_serie: 'INC-FAN-001',
    ubicacion_tipo: 'economato',
    base_id: null,
    vehiculo_id: null,
    fecha_ultima_revision: '2026-06-10',
    fecha_proximo_service: '2026-09-15',
    estado: 'reparacion',
    observacion: 'En reparación'
  },
  {
    id: 'eq18',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Otoscopio',
    marca: 'Welch Allyn',
    modelo: 'Pocket LED',
    numero_serie: 'OTO-BKP-001',
    ubicacion_tipo: 'backup',
    base_id: null,
    vehiculo_id: null,
    fecha_ultima_revision: '2026-08-12',
    fecha_proximo_service: '2027-01-12',
    estado: 'activo',
    observacion: 'Equipo de respaldo'
  },
  {
    id: 'eq19',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Glucómetro',
    marca: 'FREE STYLE',
    modelo: 'Optium Neo',
    numero_serie: 'GLU-FS-B1',
    ubicacion_tipo: 'base',
    base_id: 'b1',
    vehiculo_id: null,
    fecha_ultima_revision: '2026-08-18',
    fecha_proximo_service: '2026-11-18',
    estado: 'activo',
    observacion: ''
  },
  {
    id: 'eq20',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    equipo: 'Saturómetro',
    marca: 'CHOISE MED',
    modelo: 'MD300C2',
    numero_serie: 'SAT-CM-B3',
    ubicacion_tipo: 'base',
    base_id: 'b3',
    vehiculo_id: null,
    fecha_ultima_revision: '2026-06-22',
    fecha_proximo_service: '2026-09-18',
    estado: 'activo',
    observacion: 'Uso de guardia'
  }
];

// NOTA: este historial de revisiones es solo para la UI/mock.
// No existe como tabla/relación en el esquema real de su_equipos_biomedicos.
export const su_equipos_biomedicos_revisiones = [
  { id: 'rev1', equipo_id: 'eq1', fecha_revision: '2026-03-20', fecha_proximo_service: '2026-07-20', observacion: 'Cambio de electrodos', registrado_por: 'p2' },
  { id: 'rev2', equipo_id: 'eq1', fecha_revision: '2026-07-20', fecha_proximo_service: '2026-09-14', observacion: 'Control OK', registrado_por: 'p2' },
  { id: 'rev3', equipo_id: 'eq2', fecha_revision: '2026-06-30', fecha_proximo_service: '2026-08-25', observacion: 'Batería con autonomía baja', registrado_por: 'p11' },
  { id: 'rev4', equipo_id: 'eq4', fecha_revision: '2026-05-11', fecha_proximo_service: '2026-08-18', observacion: 'Se detecta falta de etiqueta', registrado_por: 'p6' },
  { id: 'rev5', equipo_id: 'eq6', fecha_revision: '2026-05-02', fecha_proximo_service: '2026-08-10', observacion: 'Queda fuera de servicio', registrado_por: 'p9' },
  { id: 'rev6', equipo_id: 'eq9', fecha_revision: '2026-04-18', fecha_proximo_service: '2026-08-12', observacion: 'Sensor no responde', registrado_por: 'p8' },
  { id: 'rev7', equipo_id: 'eq15', fecha_revision: '2026-05-16', fecha_proximo_service: '2026-08-05', observacion: 'Pendiente recalibración', registrado_por: 'p6' },
  { id: 'rev8', equipo_id: 'eq17', fecha_revision: '2026-06-10', fecha_proximo_service: '2026-09-15', observacion: 'Derivado a reparación externa', registrado_por: 'p11' }
];
