export const RRHH_BASES = [
  { id: 'b1', nombre: 'Pando' },
  { id: 'b2', nombre: 'Barros Blancos' },
  { id: 'b3', nombre: 'Salinas' },
  { id: 'b4', nombre: 'Atlantida' }
];

export const RRHH_ROLE_OPTIONS = [
  'Chofer',
  'Enfermero',
  'Medico',
  'Administrativo',
  'Backoffice',
  'Auxiliar_de_servicio',
  'Jefe_medico',
  'Jefe_de_enfermeria',
  'Quimica',
  'Mantenimiento'
];

export const su_empresas_contratistas = [
  {
    id: 'ec1',
    razon_social: 'Servicios Medicos del Este SRL',
    rut: '217845120019',
    contacto_nombre: 'Paula Bentancur',
    contacto_telefono: '099 410 221',
    contacto_email: 'paula.bentancur@smedeste.test',
    activa: true
  },
  {
    id: 'ec2',
    razon_social: 'Coberturas Atlanticas SAS',
    rut: '219338740017',
    contacto_nombre: 'Diego Sequeira',
    contacto_telefono: '098 233 818',
    contacto_email: 'dsequeira@coberturasatlanticas.test',
    activa: true
  },
  {
    id: 'ec3',
    razon_social: 'Soporte Sanitario Metropolitano SRL',
    rut: '216902150014',
    contacto_nombre: 'Veronica Nuchez',
    contacto_telefono: '091 772 044',
    contacto_email: 'veronica@ssm.test',
    activa: false
  }
];

export const su_personal = [
  {
    id: 'p1',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Martin',
    apellido: 'Suarez',
    documento: '39982114',
    fecha_nacimiento: '1992-09-03',
    telefono: '098 540 119',
    email: 'martin.suarez@suemergencia.test',
    domicilio: 'Treinta y Tres 221, Pando',
    foto_url: '',
    base_id: 'b1',
    estado: 'activo',
    fecha_ingreso: '2021-04-05',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p2',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Lucia',
    apellido: 'Mendez',
    documento: '41123348',
    fecha_nacimiento: '1989-04-12',
    telefono: '099 431 220',
    email: 'lucia.mendez@suemergencia.test',
    domicilio: 'Sarandi 1450, Barros Blancos',
    foto_url: '',
    base_id: 'b2',
    estado: 'activo',
    fecha_ingreso: '2020-02-10',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p3',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Noelia',
    apellido: 'Pereyra',
    documento: '45569831',
    fecha_nacimiento: '1995-01-29',
    telefono: '094 220 876',
    email: 'noelia.pereyra@coberturasatlanticas.test',
    domicilio: 'Av. Julieta 210, Salinas',
    foto_url: '',
    base_id: 'b3',
    estado: 'activo',
    fecha_ingreso: '2024-01-15',
    fecha_egreso: '',
    tipo_personal: 'externo',
    empresa_contratista_id: 'ec2'
  },
  {
    id: 'p4',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Diego',
    apellido: 'Acosta',
    documento: '42106650',
    fecha_nacimiento: '1986-06-17',
    telefono: '091 775 302',
    email: 'diego.acosta@ssm.test',
    domicilio: 'Ruta 8 km 28, Barros Blancos',
    foto_url: '',
    base_id: 'b2',
    estado: 'suspendido',
    fecha_ingreso: '2023-06-21',
    fecha_egreso: '',
    tipo_personal: 'externo',
    empresa_contratista_id: 'ec3'
  },
  {
    id: 'p5',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Sofia',
    apellido: 'Lemos',
    documento: '40037742',
    fecha_nacimiento: '1990-12-08',
    telefono: '097 331 944',
    email: 'sofia.lemos@suemergencia.test',
    domicilio: 'Rincon 112, Pando',
    foto_url: '',
    base_id: 'b1',
    estado: 'licencia',
    fecha_ingreso: '2019-08-01',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p6',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Sebastian',
    apellido: 'Alonso',
    documento: '38812294',
    fecha_nacimiento: '1984-11-20',
    telefono: '095 887 200',
    email: 'sebastian.alonso@suemergencia.test',
    domicilio: 'Tomas Berreta 81, Atlantida',
    foto_url: '',
    base_id: 'b4',
    estado: 'activo',
    fecha_ingreso: '2018-03-12',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p7',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Valentina',
    apellido: 'Rios',
    documento: '47220881',
    fecha_nacimiento: '1998-05-18',
    telefono: '092 177 603',
    email: 'valentina.rios@suemergencia.test',
    domicilio: 'Calle 7 y 10, Salinas',
    foto_url: '',
    base_id: 'b3',
    estado: 'activo',
    fecha_ingreso: '2025-02-01',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p8',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Rodolfo',
    apellido: 'Mora',
    documento: '36774491',
    fecha_nacimiento: '1981-03-06',
    telefono: '099 512 670',
    email: 'rodolfo.mora@smedeste.test',
    domicilio: 'Wilson Ferreira 55, Pando',
    foto_url: '',
    base_id: 'b1',
    estado: 'activo',
    fecha_ingreso: '2022-10-10',
    fecha_egreso: '',
    tipo_personal: 'externo',
    empresa_contratista_id: 'ec1'
  },
  {
    id: 'p9',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Camila',
    apellido: 'Araujo',
    documento: '48911427',
    fecha_nacimiento: '1999-07-22',
    telefono: '091 301 118',
    email: 'camila.araujo@suemergencia.test',
    domicilio: 'Artigas 903, Atlantida',
    foto_url: '',
    base_id: 'b4',
    estado: 'activo',
    fecha_ingreso: '2024-09-14',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p10',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Federico',
    apellido: 'Nuñez',
    documento: '38221140',
    fecha_nacimiento: '1987-10-30',
    telefono: '094 611 551',
    email: 'federico.nunez@suemergencia.test',
    domicilio: 'Pedro Campisteguy 18, Barros Blancos',
    foto_url: '',
    base_id: 'b2',
    estado: 'baja',
    fecha_ingreso: '2017-01-09',
    fecha_egreso: '2026-06-30',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  },
  {
    id: 'p11',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Adriana',
    apellido: 'Sosa',
    documento: '42911663',
    fecha_nacimiento: '1991-02-11',
    telefono: '096 881 004',
    email: 'adriana.sosa@coberturasatlanticas.test',
    domicilio: 'Gral. Flores 213, Salinas',
    foto_url: '',
    base_id: 'b3',
    estado: 'activo',
    fecha_ingreso: '2023-04-20',
    fecha_egreso: '',
    tipo_personal: 'externo',
    empresa_contratista_id: 'ec2'
  },
  {
    id: 'p12',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    nombre: 'Gonzalo',
    apellido: 'Martinez',
    documento: '37650677',
    fecha_nacimiento: '1985-08-09',
    telefono: '095 443 992',
    email: 'gonzalo.martinez@suemergencia.test',
    domicilio: 'Roger Balet 633, Atlantida',
    foto_url: '',
    base_id: 'b4',
    estado: 'activo',
    fecha_ingreso: '2021-11-03',
    fecha_egreso: '',
    tipo_personal: 'interno',
    empresa_contratista_id: ''
  }
];

export const su_personal_roles = [
  { id: 'pr1', personal_id: 'p1', rol: 'Chofer', rol_principal: true },
  { id: 'pr2', personal_id: 'p1', rol: 'Auxiliar_de_servicio', rol_principal: false },
  { id: 'pr3', personal_id: 'p2', rol: 'Jefe_de_enfermeria', rol_principal: true },
  { id: 'pr4', personal_id: 'p2', rol: 'Enfermero', rol_principal: false },
  { id: 'pr5', personal_id: 'p3', rol: 'Enfermero', rol_principal: true },
  { id: 'pr6', personal_id: 'p4', rol: 'Mantenimiento', rol_principal: true },
  { id: 'pr7', personal_id: 'p5', rol: 'Administrativo', rol_principal: true },
  { id: 'pr8', personal_id: 'p5', rol: 'Backoffice', rol_principal: false },
  { id: 'pr9', personal_id: 'p6', rol: 'Medico', rol_principal: true },
  { id: 'pr10', personal_id: 'p6', rol: 'Jefe_medico', rol_principal: false },
  { id: 'pr11', personal_id: 'p7', rol: 'Quimica', rol_principal: true },
  { id: 'pr12', personal_id: 'p8', rol: 'Chofer', rol_principal: true },
  { id: 'pr13', personal_id: 'p9', rol: 'Backoffice', rol_principal: true },
  { id: 'pr14', personal_id: 'p10', rol: 'Auxiliar_de_servicio', rol_principal: true },
  { id: 'pr15', personal_id: 'p11', rol: 'Enfermero', rol_principal: true },
  { id: 'pr16', personal_id: 'p11', rol: 'Administrativo', rol_principal: false },
  { id: 'pr17', personal_id: 'p12', rol: 'Mantenimiento', rol_principal: true }
];

export const su_personal_habilitaciones = [
  { id: 'ph1', personal_id: 'p1', tipo: 'Libreta profesional', numero: 'CHO-2291', organismo_emisor: 'Intendencia', fecha_emision: '2022-11-01', fecha_vencimiento: '2026-09-04', documento_url: 'libreta-p1.pdf', estado: 'vigente' },
  { id: 'ph2', personal_id: 'p2', tipo: 'Registro MSP', numero: 'ENF-7711', organismo_emisor: 'MSP', fecha_emision: '2025-02-10', fecha_vencimiento: '2027-02-10', documento_url: 'registro-p2.pdf', estado: 'vigente' },
  { id: 'ph3', personal_id: 'p3', tipo: 'Registro MSP', numero: 'ENF-8821', organismo_emisor: 'MSP', fecha_emision: '2024-01-16', fecha_vencimiento: '2026-09-12', documento_url: 'registro-p3.pdf', estado: 'vigente' },
  { id: 'ph4', personal_id: 'p4', tipo: 'Trabajo en altura', numero: 'ALT-1102', organismo_emisor: 'LATU', fecha_emision: '2024-08-28', fecha_vencimiento: '2026-08-28', documento_url: 'altura-p4.pdf', estado: 'vencida' },
  { id: 'ph5', personal_id: 'p6', tipo: 'Colegio medico', numero: 'MED-0021', organismo_emisor: 'SMU', fecha_emision: '2025-03-12', fecha_vencimiento: '2026-12-01', documento_url: 'colegio-p6.pdf', estado: 'vigente' },
  { id: 'ph6', personal_id: 'p8', tipo: 'Libreta profesional', numero: 'CHO-1450', organismo_emisor: 'Intendencia', fecha_emision: '2023-10-10', fecha_vencimiento: '2026-10-05', documento_url: 'libreta-p8.pdf', estado: 'vigente' },
  { id: 'ph7', personal_id: 'p11', tipo: 'Registro MSP', numero: 'ENF-9970', organismo_emisor: 'MSP', fecha_emision: '2024-04-20', fecha_vencimiento: '2026-09-25', documento_url: 'registro-p11.pdf', estado: 'en_tramite' }
];

export const su_personal_capacitaciones = [
  { id: 'pc1', personal_id: 'p1', tipo_capacitacion: 'Conduccion defensiva', institucion: 'Academia Vial', fecha_emision: '2025-09-01', fecha_vencimiento: '2026-09-10', documento_url: 'cap-p1.pdf' },
  { id: 'pc2', personal_id: 'p2', tipo_capacitacion: 'RCP y DEA', institucion: 'SU Capacitacion', fecha_emision: '2026-01-12', fecha_vencimiento: '2027-01-12', documento_url: 'cap-p2.pdf' },
  { id: 'pc3', personal_id: 'p3', tipo_capacitacion: 'Triage', institucion: 'UCM', fecha_emision: '2025-09-10', fecha_vencimiento: '2026-09-02', documento_url: 'cap-p3.pdf' },
  { id: 'pc4', personal_id: 'p5', tipo_capacitacion: 'Proteccion de datos', institucion: 'AGESIC', fecha_emision: '2024-08-15', fecha_vencimiento: '2026-08-15', documento_url: 'cap-p5.pdf' },
  { id: 'pc5', personal_id: 'p7', tipo_capacitacion: 'Buenas practicas de laboratorio', institucion: 'Facultad de Quimica', fecha_emision: '2026-02-01', fecha_vencimiento: '2026-11-01', documento_url: 'cap-p7.pdf' },
  { id: 'pc6', personal_id: 'p12', tipo_capacitacion: 'Mantenimiento preventivo', institucion: 'UTU', fecha_emision: '2025-11-03', fecha_vencimiento: '2026-09-21', documento_url: 'cap-p12.pdf' }
];

export const su_personal_carnet_salud = [
  { id: 'cs1', personal_id: 'p1', fecha_emision: '2025-09-05', fecha_vencimiento: '2026-09-15', documento_url: 'carnet-p1.pdf' },
  { id: 'cs2', personal_id: 'p2', fecha_emision: '2026-03-01', fecha_vencimiento: '2027-03-01', documento_url: 'carnet-p2.pdf' },
  { id: 'cs3', personal_id: 'p3', fecha_emision: '2025-10-15', fecha_vencimiento: '2026-10-10', documento_url: 'carnet-p3.pdf' },
  { id: 'cs4', personal_id: 'p4', fecha_emision: '2025-08-30', fecha_vencimiento: '2026-09-29', documento_url: 'carnet-p4.pdf' },
  { id: 'cs5', personal_id: 'p5', fecha_emision: '2025-07-30', fecha_vencimiento: '2026-08-21', documento_url: 'carnet-p5.pdf' },
  { id: 'cs6', personal_id: 'p6', fecha_emision: '2026-01-02', fecha_vencimiento: '2027-01-02', documento_url: 'carnet-p6.pdf' },
  { id: 'cs7', personal_id: 'p7', fecha_emision: '2026-02-15', fecha_vencimiento: '2027-02-15', documento_url: 'carnet-p7.pdf' },
  { id: 'cs8', personal_id: 'p8', fecha_emision: '2026-04-10', fecha_vencimiento: '2026-09-08', documento_url: 'carnet-p8.pdf' },
  { id: 'cs9', personal_id: 'p9', fecha_emision: '2026-05-14', fecha_vencimiento: '2027-05-14', documento_url: 'carnet-p9.pdf' },
  { id: 'cs10', personal_id: 'p10', fecha_emision: '2025-06-30', fecha_vencimiento: '2026-06-30', documento_url: 'carnet-p10.pdf' },
  { id: 'cs11', personal_id: 'p11', fecha_emision: '2026-03-18', fecha_vencimiento: '2026-09-18', documento_url: 'carnet-p11.pdf' },
  { id: 'cs12', personal_id: 'p12', fecha_emision: '2026-01-20', fecha_vencimiento: '2027-01-20', documento_url: 'carnet-p12.pdf' }
];
