export const SERVICE_PROVIDER_OPTIONS = [
  'SuEmergencia',
  'URGENCIA ASESP',
  'RADIO ASESP',
  'MUCAM',
  'URGENCIA GREMCA',
  'Española Movil',
  'ASESP',
  'GREMCA RADIO',
  'GREMCA',
  'SEGURO AMERICAN',
  'Convenio',
  'Otro'
];

export const SERVICE_PRIORITY_SUGGESTIONS = ['Crítico', 'Urgente', 'No urgente'];

export const su_servicios = [
  {
    id: 's1',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'SuEmergencia',
    prioridad: 'Crítico',
    origen_direccion: 'Treinta y Tres 221, Pando',
    origen_lat: -34.7191,
    origen_lng: -55.9619,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: null,
    paciente_nombre: 'Raúl Pereira',
    paciente_documento: '42150877',
    paciente_edad: 67,
    motivo_consulta: 'Dolor precordial',
    diagnostico_presuntivo: 'Síndrome coronario agudo',
    estado: 'solicitado',
    hora_solicitud: '2026-08-30T18:41:00',
    hora_despacho: '',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: ''
  },
  {
    id: 's2',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'URGENCIA ASESP',
    prioridad: 'Urgente',
    origen_direccion: 'Ruta 8 km 34, Barros Blancos',
    origen_lat: -34.7068,
    origen_lng: -55.9082,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: 'v1',
    paciente_nombre: 'Elena Suárez',
    paciente_documento: '38911554',
    paciente_edad: 74,
    motivo_consulta: 'Disnea aguda',
    diagnostico_presuntivo: 'Insuficiencia respiratoria',
    estado: 'asignado',
    hora_solicitud: '2026-08-30T18:12:00',
    hora_despacho: '2026-08-30T18:19:00',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: ''
  },
  {
    id: 's3',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'MUCAM',
    prioridad: 'Urgente',
    origen_direccion: 'Sarandí 1450, Barros Blancos',
    origen_lat: -34.7042,
    origen_lng: -55.9041,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: 'v3',
    paciente_nombre: 'Martín Correa',
    paciente_documento: '40114471',
    paciente_edad: 58,
    motivo_consulta: 'Crisis hipertensiva',
    diagnostico_presuntivo: 'HTA severa',
    estado: 'en_curso',
    hora_solicitud: '2026-08-30T17:53:00',
    hora_despacho: '2026-08-30T17:58:00',
    hora_llegada_escena: '2026-08-30T18:08:00',
    hora_inicio_traslado: '2026-08-30T18:16:00',
    hora_finalizacion: ''
  },
  {
    id: 's4',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Traslado',
    prestador_contratante: 'RADIO ASESP',
    prioridad: 'No urgente',
    origen_direccion: 'Centro auxiliar de Salinas',
    origen_lat: -34.7812,
    origen_lng: -55.8451,
    destino_direccion: 'Hospital de Clínicas',
    destino_lat: -34.8937,
    destino_lng: -56.1512,
    vehiculo_id: 'v7',
    paciente_nombre: 'Nora Cabrera',
    paciente_documento: '37655192',
    paciente_edad: 83,
    motivo_consulta: 'Traslado coordinado',
    diagnostico_presuntivo: 'Control posoperatorio',
    estado: 'en_curso',
    hora_solicitud: '2026-08-30T17:24:00',
    hora_despacho: '2026-08-30T17:40:00',
    hora_llegada_escena: '2026-08-30T17:58:00',
    hora_inicio_traslado: '2026-08-30T18:07:00',
    hora_finalizacion: ''
  },
  {
    id: 's5',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'SuEmergencia',
    prioridad: 'Crítico',
    origen_direccion: 'Artigas 903, Atlántida',
    origen_lat: -34.7791,
    origen_lng: -55.7582,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: null,
    paciente_nombre: 'Gastón Núñez',
    paciente_documento: '43288770',
    paciente_edad: 44,
    motivo_consulta: 'Convulsión',
    diagnostico_presuntivo: 'Evento neurológico',
    estado: 'solicitado',
    hora_solicitud: '2026-08-30T18:49:00',
    hora_despacho: '',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: ''
  },
  {
    id: 's6',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Apoyo',
    prestador_contratante: 'Convenio',
    prioridad: 'No urgente',
    origen_direccion: 'Evento deportivo, Pando',
    origen_lat: -34.7162,
    origen_lng: -55.9583,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: 'v6',
    paciente_nombre: 'Sin paciente asignado',
    paciente_documento: '',
    paciente_edad: 19,
    motivo_consulta: 'Cobertura preventiva',
    diagnostico_presuntivo: 'Apoyo de guardia',
    estado: 'asignado',
    hora_solicitud: '2026-08-30T16:55:00',
    hora_despacho: '2026-08-30T17:12:00',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: ''
  },
  {
    id: 's7',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'URGENCIA GREMCA',
    prioridad: 'Urgente',
    origen_direccion: 'Wilson Ferreira 55, Pando',
    origen_lat: -34.7204,
    origen_lng: -55.9644,
    destino_direccion: 'Sanatorio Canelones',
    destino_lat: -34.5244,
    destino_lng: -56.2796,
    vehiculo_id: 'v2',
    paciente_nombre: 'Teresa Beltrán',
    paciente_documento: '35621908',
    paciente_edad: 72,
    motivo_consulta: 'Trauma de cadera',
    diagnostico_presuntivo: 'Fractura probable',
    estado: 'finalizado',
    hora_solicitud: '2026-08-30T14:10:00',
    hora_despacho: '2026-08-30T14:18:00',
    hora_llegada_escena: '2026-08-30T14:31:00',
    hora_inicio_traslado: '2026-08-30T14:45:00',
    hora_finalizacion: '2026-08-30T15:26:00'
  },
  {
    id: 's8',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'Española Movil',
    prioridad: 'Observación',
    origen_direccion: 'Gral. Flores 213, Salinas',
    origen_lat: -34.7768,
    origen_lng: -55.8471,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: null,
    paciente_nombre: 'Micaela Ríos',
    paciente_documento: '50217763',
    paciente_edad: 21,
    motivo_consulta: 'Mareo y debilidad',
    diagnostico_presuntivo: 'Hipotensión',
    estado: 'cancelado',
    hora_solicitud: '2026-08-30T13:48:00',
    hora_despacho: '',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: '2026-08-30T13:59:00'
  },
  {
    id: 's9',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'ASESP',
    prioridad: 'Crítico',
    origen_direccion: 'Atlántida centro',
    origen_lat: -34.7728,
    origen_lng: -55.7601,
    destino_direccion: 'Médica Uruguaya',
    destino_lat: -34.8892,
    destino_lng: -56.1584,
    vehiculo_id: 'v4',
    paciente_nombre: 'Paula Vega',
    paciente_documento: '44789110',
    paciente_edad: 33,
    motivo_consulta: 'Politrauma',
    diagnostico_presuntivo: 'Trauma grave',
    estado: 'finalizado',
    hora_solicitud: '2026-08-30T11:03:00',
    hora_despacho: '2026-08-30T11:09:00',
    hora_llegada_escena: '2026-08-30T11:21:00',
    hora_inicio_traslado: '2026-08-30T11:28:00',
    hora_finalizacion: '2026-08-30T12:07:00'
  },
  {
    id: 's10',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'GREMCA RADIO',
    prioridad: 'Urgente',
    origen_direccion: 'Neptunia norte',
    origen_lat: -34.7807,
    origen_lng: -55.8333,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: null,
    paciente_nombre: 'Beatriz Silva',
    paciente_documento: '36110882',
    paciente_edad: 90,
    motivo_consulta: 'Caída en domicilio',
    diagnostico_presuntivo: 'Traumatismo leve',
    estado: 'solicitado',
    hora_solicitud: '2026-08-30T18:27:00',
    hora_despacho: '',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: ''
  },
  {
    id: 's11',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Traslado',
    prestador_contratante: 'SEGURO AMERICAN',
    prioridad: 'No urgente',
    origen_direccion: 'Salinas, policlínica local',
    origen_lat: -34.7809,
    origen_lng: -55.8448,
    destino_direccion: 'Sanatorio Americano',
    destino_lat: -34.9018,
    destino_lng: -56.1814,
    vehiculo_id: 'v9',
    paciente_nombre: 'Ruben Acuña',
    paciente_documento: '39511022',
    paciente_edad: 61,
    motivo_consulta: 'Traslado intersanatorial',
    diagnostico_presuntivo: 'Control cardiológico',
    estado: 'asignado',
    hora_solicitud: '2026-08-30T15:36:00',
    hora_despacho: '2026-08-30T15:58:00',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: ''
  },
  {
    id: 's12',
    organization_id: 'ec63de4e-8ac3-4054-a4c7-8ceae5c76ddd',
    tipo: 'Asistencia',
    prestador_contratante: 'GREMCA',
    prioridad: 'Urgente',
    origen_direccion: 'Ruta 8 km 37, Barros Blancos',
    origen_lat: -34.7052,
    origen_lng: -55.9046,
    destino_direccion: '',
    destino_lat: null,
    destino_lng: null,
    vehiculo_id: null,
    paciente_nombre: 'Carlos Menéndez',
    paciente_documento: '41881123',
    paciente_edad: 49,
    motivo_consulta: 'Dolor abdominal',
    diagnostico_presuntivo: 'Abdomen agudo a descartar',
    estado: 'cancelado',
    hora_solicitud: '2026-08-30T10:22:00',
    hora_despacho: '2026-08-30T10:30:00',
    hora_llegada_escena: '',
    hora_inicio_traslado: '',
    hora_finalizacion: '2026-08-30T10:41:00'
  }
];

export const su_servicios_dotacion = [
  { id: 'sd1', servicio_id: 's2', personal_id: 'p1', rol_en_servicio: 'Chofer' },
  { id: 'sd2', servicio_id: 's2', personal_id: 'p2', rol_en_servicio: 'Enfermero' },
  { id: 'sd3', servicio_id: 's3', personal_id: 'p1', rol_en_servicio: 'Chofer' },
  { id: 'sd4', servicio_id: 's3', personal_id: 'p2', rol_en_servicio: 'Enfermero' },
  { id: 'sd5', servicio_id: 's4', personal_id: 'p6', rol_en_servicio: 'Medico' },
  { id: 'sd6', servicio_id: 's4', personal_id: 'p9', rol_en_servicio: 'Backoffice' },
  { id: 'sd7', servicio_id: 's6', personal_id: 'p8', rol_en_servicio: 'Chofer' },
  { id: 'sd8', servicio_id: 's7', personal_id: 'p1', rol_en_servicio: 'Chofer' },
  { id: 'sd9', servicio_id: 's7', personal_id: 'p11', rol_en_servicio: 'Enfermero' },
  { id: 'sd10', servicio_id: 's9', personal_id: 'p6', rol_en_servicio: 'Medico' },
  { id: 'sd11', servicio_id: 's9', personal_id: 'p11', rol_en_servicio: 'Enfermero' },
  { id: 'sd12', servicio_id: 's11', personal_id: 'p8', rol_en_servicio: 'Chofer' }
];
